trigger: none

jobs:
- deployment: mydeployment
  pool: 
    vmImage: "macOS-10.14"
  environment: 'smarthotel-dev'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: uname -a

  # stages:
  #   - stage:
  #     deployment: 
  #     pool: 
  #       name: mypool
  #       demands: 
  #       - os.agent -equals Darwn