# steps:
#   - 
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: '默认订阅(1)(5c0108aa-9ca4-46f0-9ca1-690390568ec3)'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az version'

trigger: none



steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'shellcall1'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'mytest.ps1'



    # scriptPath: '/home/vsts/work/1/s/mytest.ps1'
  # - task: AzureCLI@2
  #   displayName: Azure CLI
  #   inputs:
  #     azureSubscription: "shellcall"
  #     scriptType: pscore
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       echo "******!!!-----*******"
  #       ls /home/vsts/work/1/s/
  #       echo "******-----*******"
  #       pwd
  #       echo "******+++++*******"
        
        # /home/vsts/work/1/s/mytest.ps