trigger: none

jobs :
- job : A
  variables:
    # a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime),5)]
    b: $[format('{0:yyyyMMddhh}', pipeline.startTime)]
  steps:
  - checkout: none
  - bash : echo "$(a) $(b)"
