trigger: none

variables:
  global_variable : root


jobs:
- job: job1
  pool:
    VmImage : "Ubuntu-16.04"
  variables:
    job_variable : job1
  steps:
    - bash: echo "global_variable:" $(global_variable);
            echo "job_variable:" $(job_variable);
            echo "JOB_VARIABLE:" $JOB_VARIABLE

- job: job2
  pool:
    VmImage : "Ubuntu-16.04"
  variables:
    job_variable : job2
  steps:
    - bash: echo "global_variable:" $(global_variable);
            echo "job_variable:" $(job_variable);
            echo "JOB_VARIABLE:" $JOB_VARIABLE


