trigger: none

jobs :
- job : A
  variables:
    a: $[counter(format('{0:yyyyMMddHHmmss}', pipeline.startTime),5)]
    b: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  steps:
  - checkout: none
  - bash : echo "$(a) $(b)"
