trigger: none

steps:
  - checkout: none
  - bash: echo "##vso[task.setvariable variable=myVar]variable_value"
  - bash: echo my pipeline variable is $(myVar)
  - pwsh: Writ-Host "my pipeline varialbe is  $env:MYVAR"