# File: azure-pipelines.yml
trigger: none

# azure-pipeline.yml

# resources:
#  containers:
#      - container: my-container
#        endpoint: my-service-connection
#        image: mycontainerimages

extends:
    template: params.yml
    parameters:
        yesNo: true
        image: 'windows-latest'